name: geist_flutter
description: Themes for the geist design framework
version: 0.0.1
author:
  - Matthew Gleich <matthewgleich@gmail.com>
  - Caleb Denio <caleb@deniosoftware.com>
homepage: https://github.com/banurapp/geist_flutter

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.17.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
