name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - uses: subosito/flutter-action@v1.3.2
        with:
          channel: 'beta'
      - run: cd example
      - run: flutter pub get
      - run: flutter build appbundle --target-platform android-arm,android-arm64,android-x64
